### PR TITLE
Add support for properties mutations with SET

### PR DESCRIPTION
**Pull request by bboure**
See https://neo4j.com/docs/cypher-manual/current/clauses/set/#set-setting-properties-using-map

### CODE REVIEW

**Comment by bboure** [comment]
@adam-cowley I think the test suite is broken. All builds fail.
I don't think I broke anything with this PR.

**Comment by adam-cowley** [comment]
Thanks @bboure, I really like this.  I'll check it out over the next couple of days and merge it.  I think I broke some tests so I'll look into that too.

**Comment by bboure** [comment]
@adam-cowley did you get a chance to review this ?

**Comment by adam-cowley** [comment]
Merged and published! Thanks for your contribution

**Pull request merged**
